### ISSUE TITLE
CSVs with commas at the end of lines

### ISSUE THREAD

**Issue by kanarinka** [c4fcm/DataBasic#176]
The problem with the CSV from the prior issue I referenced - https://github.com/c4fcm/DataBasic/issues/174 - was that it was ending every line with a comma. It looks like this is how Excel makes CSVs (at least my Excel - MS Office 2016 on Mac). I removed the trailing commas on every line and now it works.

Any way to have the parser to work with trailing commas?

**Comment by jayvachon** [comment]
should be all set now. csvs with trailing commas were failing because they were being interpreted as having a header-less column. what I'm doing now is skipping over individual columns if they don't have headers, and only throwing the "bad formatting" message if all of the columns are missing headers.
