### ISSUE TITLE
Copy and Paste function on CTD input page doesn't address edge case of tabs within data 

### ISSUE THREAD

**Issue by jpailthorpe** [c4fcm/DataBasic#237]
Doesn't address the edge case of actual tabs within the data, i.e.
```
"source"\t"target"
"node"\t"node\twith\ttabs"
```
It's pretty low-priority so I'll come back and follow up on this scenario later.

**Comment by jpailthorpe** [comment]
ref #226

**Comment by s2tephen** [comment]
Implemented a rudimentary regex solution to address this edge case, but it's not 100% bulletproof – it doesn't handle single quotes and hasn't been exhaustively tested with nested quotations, etc.

I could probably figure out how to handle all of these scenarios but I don't want to go down a rabbit hole of unnecessary complexity, especially since it will be so rare. After thinking through it, this edge case will almost _never_ show up: Excel/Google Sheets never output quoted fields (you cannot put a tab into either of these tools).

Really the only time this would come up is if someone is directly copying text from a .tsv file but if they're doing that, they most likely already know enough to convert it to a .csv and use the upload feature instead.
